spring:
  h2:
    console:
      path: /h2-console   # h2 web consloe 路径
      enabled: true       # 开启 h2 web consloe，默认为 false
      settings:
        web-allow-others: true    #允许远程访问 h2 web consloe
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:F:/H2/svn-util
    platform: h2
    username: admin
    password: 123456
    schema: classpath:/schema.sql
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    com.zero: debug
    org.springframework.web: info
    springframework.transaction: info